version: '3.8'

services:
  birdbuddy-downloader:
    image: docker.io/moosemouse/birdbuddy-downloader:latest
    build:
      context: .
      dockerfile: Containerfile
    container_name: birdbuddy-downloader
    env_file:
      - .env
    environment:
      - DOWNLOAD_DIR=/app/downloads
      - DB_PATH=/app/data/birdbuddy_downloader.db
      - WEB_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads:z
      - ./data:/app/data:z
    restart: unless-stopped
